[pkg]
Repo = "../"
Release = 0
SocSupport = ftrue

[esp32c3]
Type = "uart"
COM = "COM176"
Baud = "921600"
Firmware = ""
FsPath = "../demo/esp32"
<<<<<<< HEAD
FsOffset = "0x310000"
FsSize = "0XF0000"
<<<<<<< HEAD
=======
FsOffset = "0x390000"
FsSize = "0x70000"
>>>>>>> luadb_zone
=======
>>>>>>> 21a57972d36786d6a5ab5dc70372c0629867aad3

[esp32s3]
Type = "uart"
COM = "COM80"
Baud = "921600"
Firmware = ""
FsPath = "../demo/esp32"
FsOffset = "0x670000"
FsSize = "0x190000"
