[pkg]
Repo = "../"
Release = false
SocSupport = true

[esp32c3]
Type = "uart"
COM = "COM7"
Baud = "2000000"
Luadb = true
Firmware = "LuatOS-SoC_V0004-BETA_ESP32C3.soc"
FsPath = "../demo/wifi/station"


[esp32c3-usb]
Type = "uart"
COM = "COM3"
Baud = "2000000"
Luadb = true
Firmware = "LuatOS-SoC_V0003_ESP32C3_USB.soc"
FsPath = "../demo/pwm2"


[esp32s3]
Type = "uart"
COM = "COM4"
Baud = "921600"
Luadb = true
Firmware = "LuatOS-SoC_V0003_ESP32S3.soc"
FsPath = "../demo/uart"

